import sqlite3

conn=sqlite3.connect('b.db')
c=conn.cursor()
#c.execute("""CREATE TABLE FLIGHT_CO (CO_ID NUMBER(5) PRIMARY KEY,CO_FNAME VARCHAR2(20),CO_LNAME VARCHAR2(20),CO_AGE NUMBER(4),CO_CONTNO NUMBER(10),CO_EMAIL VARCHAR2(20))""")
#c.execute("""CREATE TABLE FLIGHT(FL_NO NUMBER(4) PRIMARY KEY,FL_COMPANY VARCHAR2(20),FL_MODEL VARCHAR2(20))""")
#c.execute("""CREATE TABLE FLIGHT_SCHED(FL_NO NUMBER PRIMARY KEY,FL_NAME VARCHAR2(20),FLI_TYPE VARCHAR2(20),FLI_FROM VARCHAR2(20),FLI_TO VARCHAR2(20),FLI_CAPACITY VARCHAR2(20),FLI_DATE DATE,FLI_TIME TIME,FLI_DUR TIME,SCHED_CO REFERENCES FLIGHT_CO (CO_ID))""")
#c.execute("""CREATE TABLE FLIGHTAR(FLI_NO PRIMARY KEY,FLI_NAME VARCAHR2(20),FLI_TYPE VARCHAR2(20),FLI_FROM VARCHAR2(20),FLI_A_TIME TIME,REPORTED_CO_ID NUMBER(4),FOREIGN KEY(REPORTED_CO_ID) REFERENCES FLIGHT_CO(CO_ID) )""")
c.execute("""CREATE TABLE CREW (CREW_ID NUMBER PRIMARY KEY,CREW_NAME VARCHAR2(20),CREW_AGE VARCHAR2(20),CREW_ROLE VARCHAR2(20),CREW_CN NUMBER(10), ASS_COID NUMBER(4),FOREIGN KEY (ASS_COID) REFERENCES FLIGHT_CO (CO_ID))""")
#c.execute("""CREATE TABLE FD (F_NO NUMBER(4) ,F_NA VARCHAR2(20), F_TY VARCHAR2(20), F_TO VARCHAR2(20),F_TIME TIME ,REP_CO NUMBER(4),FOREIGN KEY (REP_CO) REFERENCES FLIGHT_CO (CO_ID) ON UPDATE CASCADE,PRIMARY KEY(F_NO,REP_CO))""")

conn.commit()
conn.close()
